server:
  port: 9090
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1
  servlet:
    context-path: /site
    encoding:
      charset: UTF-8
      enabled: true
      force: true
 
logging:
  level:
    web: trace
     
#resource:    
#  path: 
#    file: ///C:/uploads/

# 업로드된 파일 저장 위치 설정
#com:
#  example:
#    upload-path: C:/uploads 
#
#upload:
#  path: C:/uploads 
  
#resource: C:/uploads    

#custom:
#  path:
#    upload-images: 

    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  web:
    resources:
      static-locations: classpath:/static/
    log-details: true
      
  # 파일 업로드 설정
  servlet:
    multipart: 
      enabled: false
      max-file-size: 10MB
      max-request-size: 10MB
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/site?serverTimezone=Asia/Seoul
    username: root
    password: 1234
 
  


      
#  storage:
#    location: ./uploads
      

mybatis: 
##  mapper-locations: classpath:mapper/**/*.xml 
  config-location: classpath:mybatis-config.xml
    
    